### ISSUE TITLE
SMBs often fail likely due to TDD calculations (DASH)

### ISSUE THREAD

**Issue by Ashley112885** [tim2000s/Boost-master-v3#3]
https://github.com/nightscout/AndroidAPS/issues/2055

Proposed fix: https://github.com/nightscout/AndroidAPS/pull/2070

![image](https://user-images.githubusercontent.com/38409940/192105733-3451931b-f3cd-4b58-ba9c-bd6a23016bbc.jpeg)

https://discord.com/channels/942372379097698325/943074159955701770/1023197743419760730

**Comment by tim2000s** [comment]
This issue has now been closed by extending the time out period.
