### ISSUE TITLE
Unable to delete treatments

### ISSUE THREAD

**Issue by Ashley112885** [tim2000s/Boost-master-v3#5]
Discovered issue yesterday at 11pm ET in Boost-Tsunami and have since reverted to a previous version of Boost. It appears that the ability to delete treatments is not functional in Boost-Tsunami.

**Comment by tim2000s** [comment]
This seems to be an issue with the Tsunami code integration. I'm afraid that I won't be digging through to try and figure it out, however, the workaround is to enable synchronization with Nightscout and delete treatment from Nightscout. 

I've found that worked.
